name: DisposeScope

packages:
  - packages/**

scripts:
  get:
    run: melos exec flutter pub get

  analyze:
    run: melos exec flutter analyze

  test:
    run: melos exec flutter test
    select-package:
      dir-exists:
        - test

  clean:
    run: melos exec flutter clean
