name: bloc_dispose_scope
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  dispose_scope: ^0.0.1
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.3
  lint: ^1.5.3
  mockito: ^5.0.8
  test: ^1.17.12

dependency_overrides:
  dispose_scope:
    path: ../dispose_scope
