name: dispose_scope
description: Simple package making it easy to dispose (aka cancel, aka close) your objects.
version: 2.1.0
repository: https://github.com/RobertOdrowaz/dispose-scope/tree/master/packages/dispose_scope
issue_tracker: https://github.com/RobertOdrowaz/dispose-scope/issues
homepage: https://github.com/RobertOdrowaz/dispose-scope

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  leancode_lint: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.17.12
