name: flutter_dispose_scope
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  dispose_scope: ^0.0.1
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.8

dependency_overrides:
  dispose_scope:
    path: ../dispose_scope
