name: Test

on:
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"

      - name: Install melos
        run: flutter pub global activate melos 2.9.0

      - name: Get dependencies
        run: melos run get

      - name: Run tests
        run: melos run test --no-select

      - name: Run analyzer
        run: melos run analyze

      - name: Check formatting
        run: flutter format --set-exit-if-changed .
